name: TYOY
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - blas=1.0=mkl
  - ca-certificates=2020.7.22=0
  - freetype=2.10.2
  - intel-openmp=2020.2
  - jpeg=9b
  - lcms2=2.11
  - libedit=3.1.20191231
  - libffi=3.3
  - libpng=1.6.37
  - libsodium=1.0.18
  - libtiff=4.1.0
  - lz4-c=1.9.2
  - mkl=2020.2
  - ncurses=6.2
  - openssl=1.1.1g
  - pandoc=2.10.1
  - pip=20.2.2=py36_0
  - python=3.6.12
  - python_abi=3.6
  - readline=8.0
  - setuptools=49.6.0=py36_0
  - sqlite=3.33.0
  - tk=8.6.10
  - wheel=0.35.1=py_0
  - xz=5.2.5
  - zeromq=4.3.2
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - absl-py==0.7.1
    - astor==0.8.0
    - attrs==19.1.0
    - backcall==0.1.0
    - bleach==3.1.4
    - certifi==2019.6.16
    - chardet==3.0.4
    - cycler==0.10.0
    - decorator==4.4.0
    - defusedxml==0.6.0
    - entrypoints==0.3
    - gast==0.2.2
    - google-pasta==0.1.7
    - grpcio==1.22.0
    - h5py==2.9.0
    - idna==2.8
    - ipykernel==5.1.1
    - ipython==7.6.1
    - ipython-genutils==0.2.0
    - ipywidgets==7.5.0
    - jedi==0.14.0
    - jinja2==2.10.1
    - joblib==0.13.2
    - jsonschema==3.0.1
    - jupyter==1.0.0
    - jupyter-client==5.3.0
    - jupyter-console==6.0.0
    - jupyter-core==4.5.0
    - keras==2.2.4
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.0
    - kiwisolver==1.1.0
    - markdown==3.1.1
    - markupsafe==1.1.1
    - mistune==0.8.4
    - mpmath==1.1.0
    - matplotlib
    - nbconvert==5.5.0
    - nbformat==4.4.0
    - notebook==5.7.8
    - numpy==1.16.4
    - opt-einsum==3.3.0
    - pandas==0.24.2
    - pandocfilters==1.4.2
    - parso==0.5.0
    - pexpect==4.7.0
    - pickleshare==0.7.5
    - pillow==6.2.1
    - progressbar2==3.46.1
    - prometheus-client==0.7.1
    - prompt-toolkit==2.0.9
    - protobuf==3.8.0
    - ptyprocess==0.6.0
    - pygments==2.4.2
    - pyparsing==2.4.0
    - pyrsistent==0.15.3
    - python-dateutil==2.8.0
    - python-utils==2.4.0
    - pytz==2020.1
    - pyyaml==5.1.1
    - pyzmq==18.0.2
    - qtconsole==4.5.1
    - requests==2.22.0
    - scikit-learn==0.21.2
    - scipy==1.3.0
    - send2trash==1.5.0
    - six==1.12.0
    - sklearn==0.0
    - sympy==1.4
    - tensorboard==1.15.0
    - tensorflow==1.15.0
    - tensorflow-estimator==1.15.0
    - termcolor==1.1.0
    - terminado==0.8.2
    - testpath==0.4.2
    - tornado==6.0.3
    - traitlets==4.3.2
    - urllib3==1.25.3
    - wcwidth==0.1.7
    - webencodings==0.5.1
    - werkzeug==0.15.4
    - widgetsnbextension==3.5.0
    - wrapt==1.11.2

